/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef SECRETREPOSITORY_CRYPT_LIB_H
#define SECRETREPOSITORY_CRYPT_LIB_H

#endif //SECRETREPOSITORY_CRYPT_LIB_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_secretrepository_app_util_CryptUtil
 * Method:    encryptA
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_secretrepository_app_util_CryptUtil_encryptA
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_secretrepository_app_util_CryptUtil
 * Method:    encryptB
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_secretrepository_app_util_CryptUtil_encryptB
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
